apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
spec:
  destination:
    name: ''
    namespace: bolinas
    server: 'https://kubernetes.default.svc'
  source:
    path: ./datadog
    repoURL: 'https://stash.guidewire.com/scm/ccs/bolinas-upskill-argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dockerd.yaml
  project: default
